### ISSUE TITLE
Automate Release Process

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#1024]
We'd like to have a more regular and frequent cadence of releases, however as can be seen in this comment https://github.com/googleforgames/quilkin/issues/964#issuecomment-2289252532 currently releases have a long list of tasks that someone needs to perform manually before a release can be done, which can get in the way of doing it frequently.

I think ideally we'd like to automate as much as that list as possible and change some of the process to be more automation friendly to the point where all that is required for making a release is merging an automatically generated PR.

### Tasks That Can Be Automated

- [ ] Container creation and push (including archival of any MPL and CDDL dependencies).
- [ ] Crate release ( handled with https://github.com/MarcoIeni/release-plz ).
- [ ] Version bump ( handled with https://github.com/MarcoIeni/release-plz ).

### Things That Need To Change
- [ ] Stop using `-dev` suffix
  - This makes automation more difficult, and means we have to manually change it for any release, would be better to allow this to be automated.

cc @markmandel

**Comment by markmandel** [comment]
No issue on my end on removing the `-dev` - this all sounds like good things.

Count me in!

With the documentation for releases, rather than having a list of release links, we should also build out a discovery page in `gh-pages` that is automatically built as well.

This all sounds like good things 👍🏻
