### ISSUE TITLE
0.1.0 Release Schedule

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#313]
All plans seem to align to announcement of the 0.1.0 release on the 15th  of July!

This is the schedule I would propose leading up to that - comments and feedback definitely welcome.

This is also keeping in mind that Sweden is on holiday, the week of the 4th of a 3 day week in the US, and the week of the 12th of the Google for Games Developer Summit (and then after that is virtual GDC) - so time is probably limited for everyone - so an aim to keep surprises to a minimum over the next couple of weeks.

* 8th of July
  * [x] Do a refactoring and feature freeze so that there are no surprises leading up to the release. (or maybe "minor  PR's only").
  * [x] Create the release issue, and start going through the [release checklist](https://github.com/googleforgames/quilkin/blob/main/build/templates/release-issue.md)
  * [x] Submit the release PR: changelog, version changes, etc
* 9th of July 
  * [x] Merge the release PR.
  * [x] Finish all of the release checklist, except for announcements, and publishing to cargo.
  * [x] Create  release with release artifacts.
  * [x] Submit the 0.1.0 release.
* 12th of July
  * [x] Focus on documentation / onboarding experience.
* 14th of July
  * [x] (late us pacific) make the repository public.
  * [x] Publish crates.
* 15th of July
  *  [x] Announcement blog posts goes live.
  *  [x] Add blog posts to README
  * [x] Finish release checklist.
  *  [x] Close this ticket.
  *  [x] Party 🥳 

@luna-duclos @iffyio @XAMPPRocky - how does that sound to you?

**Comment by markmandel** [comment]
Finished checklist, and I assume you are all partying now!
