### ISSUE TITLE
Create monthly community meeting

### ISSUE THREAD

**Issue by markmandel** [googleforgames/quilkin#372]
Monthly community meetings!

Meetings start tomorrow, so I will jump on this today!

* [ ] Hangout link / calendar entry
* [ ] Public Google doc with an Agenda
* [ ] bit.ly link to Google doc
* [ ] Invite [quilkin-discuss](https://groups.google.com/forum/#!forum/quilkin-discuss)
* [ ] Create a Google Calendar and share on github repo
* [ ] Add "Quilkin" playlist to [Google Gaming Open Source](https://www.youtube.com/channel/UCSX_i2OS_MPGsbMPIlOY3kg) YouTube account
