### ISSUE TITLE
Tracking Issue for Metrics integration tests

### ISSUE THREAD

**Issue by XAMPPRocky** [googleforgames/quilkin#739]
Over time, we've moved more and more of our metrics into static members. This has made a lot of the code architecture a lot simpler, cleaner, and easier to refactor, however the one downside to this approach has been that static metrics do not play well with regular unit tests in rust, since we run multiple in parallel in one process leading to the metric tracking metrics for all the tests rather than an individual one. I think the solution to this is to move our metrics testing into an integration test(s) (e.g. `tests/`), since integration tests run as separate processes, we can easily have one or more tests that completely isolated and thus allow us to easily validate metric logic.

This requires updating the visibility of each metric, and either updating the current tests in `tests/` or creating a new `tests/metrics.rs` integration test. I also think it would be a good opportunity to refactor some of our current integration tests to be a bit more uniform.

### Metrics
- Proxy
  - [ ] `quilkin_packets_processing_duration_seconds`
  - [ ] `quilkin_packets_dropped_total`
  - [ ] `quilkin_cluster_active`
  - [ ] `quilkin_cluster_active_endpoints`
  - [ ] `quilkin_bytes_total`
  - [ ] `quilkin_packets_total`
  - [ ] `quilkin_errors_total`

- Filters
  - [ ] Capture
  - [ ] Compress
  - [ ] Concat Bytes
  - [ ] Firewall
  - [ ] Load Balancer
  - [ ] Local Rate Limit
  - [ ] Match
  - [ ] Timestamp
  - [ ] Token Router

- Control Plane
  - [ ] `quilkin_xds_connected_state`
  - [ ] `quilkin_xds_update_attempt_total`
  - [ ] `quilkin_xds_update_success_total`
  - [ ] `quilkin_xds_update_failure_total`
  - [ ] `quilkin_xds_requests_total`
  - [ ] `quilkin_management_server_connected_proxies`
  - [ ] `quilkin_management_server_discovery_requests_total`
  - [ ] `quilkin_management_server_discovery_responses_total`
  - [ ] `quilkin_management_server_endpoints_total`
  - [ ] `quilkin_management_server_snapshot_generation_errors_total`
  - [ ] `quilkin_management_server_snapshots_generated_total`
  - [ ] `quilkin_management_server_snapshots_cache_size`
